### ISSUE TITLE
jvm crash when profiling (jdk8 with some javaagent)

### ISSUE THREAD

**Issue by guhanjie** [async-profiler/async-profiler#755] opened 2023-06-07 04:17 UTC
It will crash once profiling, using jdk8 with some javaagent([prometheus](https://github.com/prometheus/jmx_exporter))

Normally, we can run process well with this javaagent.
But, once we attach async-profiler to this process, it will crash definitely.
And, from the crash.log we see the point is CodeHeap::findNMethod(char*, void const*)+0x2c
which is introduced from commit [Avoid JVM crashes related to CompiledMethodLoad bugs and stack walking during GC](https://github.com/async-profiler/async-profiler/commit/2d0b9c9921afa9eec809dac6991ecc03a240bcf7)

@apangin Please help to confirm it, quit confused to me, -,-!

Here is jvm crash.log:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f22795bc22c, pid=86570, tid=0x00007f228d3f7700
#
# JRE version: OpenJDK Runtime Environment (8.0_352-b206) (build 1.8.0_352-b718)
# Java VM: OpenJDK 64-Bit Server VM (25.352-b718 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libasyncProfiler.so+0x822c]  CodeHeap::findNMethod(char*, void const*)+0x2c
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   mailto:jvm@list.alibaba-inc.com
#

---------------  T H R E A D  ---------------

Current thread (0x00007f2412e2bc10):  JavaThread "prometheus-http-1-3" daemon [_thread_in_Java, id=88414, stack(0x00007f228d2f7000,0x00007f228d3f8000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00003f9a7786f968

Registers:
RAX=0x0000000000000070, RBX=0x00007f228d3f5000, RCX=0x0000000000000001, RDX=0x0000000000000020
RSP=0x00007f228d3f4e68, RBP=0x00007f228d3f4f00, RSI=0x00003f9a7786f948, RDI=0x00007f350941d080
R8 =0x0000000000000007, R9 =0x00007f228d3f4f60, R10=0x00007f228d3f4fd0, R11=0x0000000000000000
R12=0x00007f23da8b30c0, R13=0x00007f228d3f5000, R14=0x00007f228d3f4eb0, R15=0x00007f227798e340
RIP=0x00007f22795bc22c, EFLAGS=0x0000000000010206, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f228d3f4e68)
0x00007f228d3f4e68:   00007f22795c9a57 00007f34ef859120
0x00007f228d3f4e78:   00007f228d3f4f60 00007f228d3f5d50
0x00007f228d3f4e88:   00007f228d3f5cd8 00007f34ef0df297
0x00007f228d3f4e98:   0000080012e2bc10 00007f228d3f5000
0x00007f228d3f4ea8:   00007f35000000b6 00007f2412e2bec8
0x00007f228d3f4eb8:   00000000fffffffb 00007f227798e340
0x00007f228d3f4ec8:   00007f34ee0623d5 00007f34ee0621d0
0x00007f228d3f4ed8:   00007f23da8b30c0 000000000001595e
0x00007f228d3f4ee8:   0000000000000007 00007f228d3f5000
0x00007f228d3f4ef8:   00007f227798e340 00007f228d3f4fb0
0x00007f228d3f4f08:   00007f22795cc033 00007f22157f3548
0x00007f228d3f4f18:   00007f227798e340 00007f2200000000
0x00007f228d3f4f28:   00007f228d3f4f60 000000000098dce0
0x00007f228d3f4f38:   00007f23da8bb314 00007f228d3f4fd0
0x00007f228d3f4f48:   000000008d3f5e60 00007f228c5e1688
0x00007f228d3f4f58:   00007f34f0857f5c 0000000000000000
0x00007f228d3f4f68:   0000000000000000 0000000000000000
0x00007f228d3f4f78:   00007f228d3f5e60 00007f228d3f4ff0
0x00007f228d3f4f88:   00007f228d3f5130 00007f228d3f5000
0x00007f228d3f4f98:   00007f2c9d3d7640 0000000000000048
0x00007f228d3f4fa8:   00007f2412e2bc10 00007f228d3f4ff0
0x00007f228d3f4fb8:   00007f22795cd01d 00007f228d3f5030
0x00007f228d3f4fc8:   00007f228d3f4fd0 0000000000000000
0x00007f228d3f4fd8:   00007f250af9b770 00007f24158e9f10
0x00007f228d3f4fe8:   00007f2505fff000 00007f228d3f5d50
0x00007f228d3f4ff8:   00007f350a7c7630 0000000000000001
0x00007f228d3f5008:   0000000000000000 0000000000000000
0x00007f228d3f5018:   0000000000000002 0000000000000000
0x00007f228d3f5028:   00007f2c9d3d7580 00007f2c9d3d7680
0x00007f228d3f5038:   00007f250ae168b0 00000000004e17e1
0x00007f228d3f5048:   00007f2505fff000 00007f2c9d3d7640
0x00007f228d3f5058:   0000000000000048 00007f2412e2bc10

Instructions: (pc=0x00007f22795bc22c)
0x00007f22795bc20c:   23 00 8b 0d ec a3 23 00 48 01 d7 4c 8b 04 07 48
0x00007f22795bc21c:   63 05 ee a3 23 00 4c 29 c6 48 8b 14 07 48 d3 fe
0x00007f22795bc22c:   0f b6 04 32 3c ff 75 13 eb 2a 66 2e 0f 1f 84 00
0x00007f22795bc23c:   00 00 00 00 48 29 c6 0f b6 04 32 84 c0 75 f5 48

[Disassembling for mach='i386:x86-64']
  0x00007f22795bc20c: and    (%rax),%eax
  0x00007f22795bc20e: mov    0x23a3ec(%rip),%ecx        # 0x00007f22797f6600
  0x00007f22795bc214: add    %rdx,%rdi
  0x00007f22795bc217: mov    (%rdi,%rax,1),%r8
  0x00007f22795bc21b: movslq 0x23a3ee(%rip),%rax        # 0x00007f22797f6610
  0x00007f22795bc222: sub    %r8,%rsi
  0x00007f22795bc225: mov    (%rdi,%rax,1),%rdx
  0x00007f22795bc229: sar    %cl,%rsi
  0x00007f22795bc22c: movzbl (%rdx,%rsi,1),%eax
  0x00007f22795bc230: cmp    $0xff,%al
  0x00007f22795bc232: jne    0x00007f22795bc247
  0x00007f22795bc234: jmp    0x00007f22795bc260
  0x00007f22795bc236: nopw   %cs:0x0(%rax,%rax,1)
  0x00007f22795bc240: sub    %rax,%rsi
  0x00007f22795bc243: movzbl (%rdx,%rsi,1),%eax
  0x00007f22795bc247: test   %al,%al
  0x00007f22795bc249: jne    0x00007f22795bc240
  0x00007f22795bc24b: rex.W

Register to memory mapping:

RAX=0x0000000000000070 is an unknown value
RBX=0x00007f228d3f5000 is pointing into the stack for thread: 0x00007f2412e2bc10
RCX=0x0000000000000001 is an unknown value
RDX=0x0000000000000020 is an unknown value
RSP=0x00007f228d3f4e68 is pointing into the stack for thread: 0x00007f2412e2bc10
RBP=0x00007f228d3f4f00 is pointing into the stack for thread: 0x00007f2412e2bc10
RSI=0x00003f9a7786f948 is an unknown value
RDI=0x00007f350941d080 is an unknown value
R8 =0x0000000000000007 is an unknown value
R9 =0x00007f228d3f4f60 is pointing into the stack for thread: 0x00007f2412e2bc10
R10=0x00007f228d3f4fd0 is pointing into the stack for thread: 0x00007f2412e2bc10
R11=0x0000000000000000 is an unknown value
R12=0x00007f23da8b30c0 is an unknown value
R13=0x00007f228d3f5000 is pointing into the stack for thread: 0x00007f2412e2bc10
R14=0x00007f228d3f4eb0 is pointing into the stack for thread: 0x00007f2412e2bc10
R15=0x00007f227798e340 is an unknown value


Stack: [0x00007f228d2f7000,0x00007f228d3f8000],  sp=0x00007f228d3f4e68,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libasyncProfiler.so+0x822c]  CodeHeap::findNMethod(char*, void const*)+0x2c
C  [libasyncProfiler.so+0x18033]  Profiler::recordSample(void*, unsigned long long, EventType, Event*)+0x3c3
C  [libasyncProfiler.so+0x1901d]  PerfEvents::signalHandler(int, siginfo_t*, void*)+0xdd
C  [libpthread.so.0+0xf630]
J 9389 C2 java.util.regex.Pattern$Begin.match(Ljava/util/regex/Matcher;ILjava/lang/CharSequence;)Z (62 bytes) @ 0x00007f34f0349498 [0x00007f34f0349400+0x98]
J 11163 C2 io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector$Receiver.recordBean(Ljava/lang/String;Ljava/util/LinkedHashMap;Ljava/util/LinkedList;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V (991 bytes) @ 0x00007f34f07d92d0 [0x00007f34f07d68a0+0x2a30]
J 12582 C2 io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.processBeanValue(Ljava/lang/String;Ljava/util/LinkedHashMap;Ljava/util/LinkedList;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V (752 bytes) @ 0x00007f34f0b91868 [0x00007f34f0b910c0+0x7a8]
J 16471 C2 io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(Ljavax/management/MBeanServerConnection;Ljavax/management/ObjectName;)V (333 bytes) @ 0x00007f34ef3fe718 [0x00007f34ef3fd260+0x14b8]
j  io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape()V+397
j  io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect()Ljava/util/List;+116
J 15704 C2 io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement()Ljava/lang/Object; (5 bytes) @ 0x00007f34f1461fb4 [0x00007f34f1461980+0x634]
J 17492 C1 io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(Ljava/io/Writer;Ljava/util/Enumeration;)V (285 bytes) @ 0x00007f34f1823084 [0x00007f34f1822e80+0x204]
j  io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(Lcom/sun/net/httpserver/HttpExchange;)V+76
j  com.sun.net.httpserver.Filter$Chain.doFilter(Lcom/sun/net/httpserver/HttpExchange;)V+17
j  sun.net.httpserver.AuthFilter.doFilter(Lcom/sun/net/httpserver/HttpExchange;Lcom/sun/net/httpserver/Filter$Chain;)V+121
j  com.sun.net.httpserver.Filter$Chain.doFilter(Lcom/sun/net/httpserver/HttpExchange;)V+41
j  sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Lcom/sun/net/httpserver/HttpExchange;)V+5
j  com.sun.net.httpserver.Filter$Chain.doFilter(Lcom/sun/net/httpserver/HttpExchange;)V+17
j  sun.net.httpserver.ServerImpl$Exchange.run()V+1059
J 10494 C1 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f34f0567a34 [0x00007f34f0565ea0+0x1b94]
J 9322 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00007f34f0316ac4 [0x00007f34f0316980+0x144]
J 6465 C1 java.lang.Thread.run()V (17 bytes) @ 0x00007f34efade664 [0x00007f34efade4e0+0x184]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x6a05b6]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1026
V  [libjvm.so+0x69d924]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x2a4
V  [libjvm.so+0x69df39]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x59
V  [libjvm.so+0x738c32]  thread_entry(JavaThread*, Thread*)+0x122
V  [libjvm.so+0xaadc72]  JavaThread::thread_main_inner()+0x202
V  [libjvm.so+0x93efd2]  java_start(Thread*)+0xf2
C  [libpthread.so.0+0x7ea5]
```

**Comment by apangin** [comment] 2023-06-07 13:29
What JDK distribution do you use? Version number `8.0_352-b206` and email `jvm@list.alibaba-inc.com` suggests it's some custom OpenJDK build.

**Comment by apangin** [comment] 2023-06-09 01:22
The issue is likely caused by a custom JDK version that differs from OpenJDK in some internals. It's hard to tell more without having this exact version. Please provide more details on how to reproduce the issue.

**Comment by guhanjie** [comment] 2023-06-12 06:05
yeah, I did use custom JDK, and I just confirmed the problem is about the JDK build, because the problem is missing when I switch custom JDK build to Oracle JDK build(1.8.0_121-b13)

Thank you to help me, I will report the issue to our custom JDK team(AJDK from alibaba).

**Comment by apangin** [comment] 2023-06-13 01:18
I tested with Alibaba Dragonwell, and async-profiler seems to work fine with that.

I'm going to close the issue as not caused by async-profiler. Feel free to reopen if you happen to reproduce it with any publicly available JDK build.

**Closed by apangin** 2023-06-13 01:18 UTC
Labels: need more details

**Comment by guhanjie** [comment] 2023-06-13 02:25
Did you test with Alibaba Dragonwell 8 version?

**Comment by apangin** [comment] 2023-06-13 23:07
Yes, I tried Alibaba Dragonwell 8.15.16 both Standard and Extended edition.

**Comment by guhanjie** [comment] 2023-06-26 04:24
@apangin Thanks again.
I contact with AJDK R&D team, and confirm it is a bug in AJDK internals(some versions).
The cause is AJDK8 ported `segment code cache` feature from JDK11, which lead to have both variables: _heap and _heaps, while openjdk8 only has _heap and openjdk11 only has _heaps. 
So, such both variables leads async-profiler can not work well, and then crash...

Now I workaround it, as I just use AJDK8, so I comments part of processing for _heaps
`diff --git a/src/vmStructs.cpp b/src/vmStructs.cpp
index 21717db..02d61f8 100644
--- a/src/vmStructs.cpp
+++ b/src/vmStructs.cpp
@@ -215,8 +215,8 @@ void VMStructs::initOffsets() {
         } else if (strcmp(type, "CodeCache") == 0) {
             if (strcmp(field, "_heap") == 0) {
                 _code_heap_addr = *(char***)(entry + address_offset);
-            } else if (strcmp(field, "_heaps") == 0) {
-                _code_heap_addr = *(char***)(entry + address_offset);
+            // } else if (strcmp(field, "_heaps") == 0) {
+            //    _code_heap_addr = *(char***)(entry + address_offset);
             } else if (strcmp(field, "_low_bound") == 0) {
                 _code_heap_low_addr = *(const void***)(entry + address_offset);
             } else if (strcmp(field, "_high_bound") == 0) {`

**Comment by apangin** [comment] 2023-06-26 19:59
That makes sense. Thank you for the follow up!
