### ISSUE TITLE
Large number of `no_Java_frame` entries in the flame graph

### ISSUE THREAD

**Issue by realxujiang** [async-profiler/async-profiler#893] opened 2024-02-22 03:02 UTC
Hi, I encountered some performance issues while running data processing on an ARM server for big data. I'm curious about the significance of the large number of 'no_java_frame' entries in the flame graph. Are there any further steps I can take to investigate this?

## Container resource k8s configuration
```
resources:
      limits:
        cpu: "40"
        memory: 160Gi
      requests:
        cpu: "35"
        memory: 160Gi
```

## aarch64 GNU/Linux version
```
# cat /etc/centos-release
CentOS Linux release 8.4.2105
```

## Java info
```
# java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment BiSheng (build 11.0.16+11)
OpenJDK 64-Bit Server VM BiSheng (build 11.0.16+11, mixed mode)
```

## profiler info
```
$ profiler version
2.9

$ profiler start --duration 300 --format html --event cpu
```
I have generated flame graphs for container performance stress testing and online scenarios separately. In the actual scenario, the `no_java_frame` is extremely long. I would like to further confirm what `no_java_frame` is specifically doing. Do you have any troubleshooting ideas?

* online case
![image](https://github.com/async-profiler/async-profiler/assets/12759642/cddce9f5-fa89-4748-a3fc-2367190e9d32)

* benchmark case
![image](https://github.com/async-profiler/async-profiler/assets/12759642/af0df9d4-b8d6-4202-a894-c4a65ccfb07c)

**Comment by apangin** [comment] 2024-02-22 11:22
Version 2.9 is no longer maintained. Please try 3.0.

**Comment by apangin** [comment] 2024-02-22 11:35
```
OpenJDK Runtime Environment BiSheng
                            ^^^^^^^
```
Seems like a customzied JDK version. If it changed something around frame layout, this could also cause issues with stack walking in async-profiler.

**Comment by realxujiang** [comment] 2024-02-23 06:06
> ```
> OpenJDK Runtime Environment BiSheng
>                             ^^^^^^^
> ```
> 
> Seems like a customzied JDK version. If it changed something around frame layout, this could also cause issues with stack walking in async-profiler.

Thank you, I'll try switching to OpenJDK for testing.

**Comment by realxujiang** [comment] 2024-02-23 06:10
> Version 2.9 is no longer maintained. Please use 3.0. Also, try adding `--cstack dwarf`

I tried adding `--cstack dwarf` to the profiler command, but `no_Java_frame` still exists."
![image](https://github.com/async-profiler/async-profiler/assets/12759642/77697be5-49d6-4f4f-ab16-c4d7a1705139)

**Comment by apangin** [comment] 2024-02-23 11:35
Can you share a sample program that demonstrates the problem?
Do you still see `no_Java_frame` with `--cstack vm` option?

**Comment by realxujiang** [comment] 2024-02-26 02:12
> Can you share a sample program that demonstrates the problem? Do you still see `no_Java_frame` with `--cstack vm` option?

The command executed is as follows:

* option 1
```
[root@node1 async-profiler-3.0-linux-arm64]# bin/asprof --cstack dwarf -e cpu  -d 300 -f profile.html 14
Profiling for 300 seconds
Done
```
![image](https://github.com/async-profiler/async-profiler/assets/12759642/e8fbad4b-7d47-4aa5-84e5-547438d00ec9)

* option 2
```
[root@node1 async-profiler-3.0-linux-arm64]# bin/asprof --cstack vm  -e cpu  -d 300 -f profile.html 14
Profiling for 300 seconds
Done
```
![image](https://github.com/async-profiler/async-profiler/assets/12759642/5f28e74c-62f9-4ba4-9c14-e1c3030a9bbe)

"No_Java_frame" has disappeared after adding the --cstack vm option.

**Comment by apangin** [comment] 2024-02-27 12:35
Thank you for the update.
So, I assume the problem is solved and I can close the issue, unless you want to provide a sample program to investigate further.

**Comment by realxujiang** [comment] 2024-02-28 01:44
> Thank you for the update. So, I assume the problem is solved and I can close the issue, unless you want to provide a sample program to investigate further.

Thank you so much for your assistance! We've encountered a challenging issue within a highly complex scenario, and unfortunately, we're unable to provide a straightforward reproducible program at this time. Once again, we deeply appreciate your support!

**Comment by apangin** [comment] 2024-02-28 02:14
OK, no problem.
Basing on the difference between profiles obtained with `--cstack dwarf` and `--cstack vm`, can you identify which stacks are missing in the first case?

**Comment by realxujiang** [comment] 2024-03-05 00:04
> OK, no problem. Basing on the difference between profiles obtained with `--cstack dwarf` and `--cstack vm`, can you identify which stacks are missing in the first case?

The specific flame graph is as follows:

* option: `--cstack dwarf` 
![image](https://github.com/async-profiler/async-profiler/assets/12759642/c941e6ba-0d10-42e3-abd3-b4faefab5d05)

* option:  `--cstack vm`
![image](https://github.com/async-profiler/async-profiler/assets/12759642/b9165a4f-cd78-425c-9a90-382e1ff714c6)

As shown above, the section JavaThread::thread_main_inner is missing.

**Comment by apangin** [comment] 2024-03-05 00:49
`JavaThread::thread_main_inner` is not a problem. `--cstack dwarf` never shows any native frame below the first Java frame - that's by design and is totally fine.

`[no_Java_frame]` corresponds to something else that I don't see on the screenshot.

**Comment by realxujiang** [comment] 2024-03-06 06:01
> `JavaThread::thread_main_inner` is not a problem. `--cstack dwarf` never shows any native frame below the first Java frame - that's by design and is totally fine.
> 
> `[no_Java_frame]` corresponds to something else that I don't see on the screenshot.

Yes, with the flame graph generated using the `--cstack vm` option, `No_Java_frame` has disappeared . 

Most of the CPU time is spent on Full GC, indicating a significant amount of memory fragmentation. 

Strict memory management is required, we plan to refer to part of HBase's implementation, managing memory caching data with chunk pools, to strictly control memory usage. 

Once again, thank you for your assistance. The async-profiler tool is excellent.

**Comment by apangin** [comment] 2024-03-10 22:15
I found the cause of `[no_Java_frame]`. These samples actually belong to GC threads.
On ARM64, JVM calls generated atomic stubs, which are not normally walkable.

I pushed the fix that recovers such stack traces with `--cstack dwarf` or `--cstack fp`.

**Closed** 2024-03-10 22:16 UTC
Labels: bug

**Comment by apangin** [comment] 2024-03-10 22:23
Here are the parts of the stack that were missing:
<img width="924" alt="atomic_entry_points" src="https://github.com/async-profiler/async-profiler/assets/1749416/72a35665-da7a-4690-9a86-58dd91594c52">
