### ISSUE TITLE
Profiling crashes in NMethod::isNMethod with JDK 23-ea

### ISSUE THREAD

**Issue by djelinski** [async-profiler/async-profiler#923] opened 2024-05-06 11:39 UTC
I'm using async-profiler with the latest JDK built from git; recently the the JDK started crashing with:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000071cbb0806ecf, pid=928720, tid=928742
#
# JRE version: OpenJDK Runtime Environment (23.0) (build 23-internal-adhoc.daniel.jdk)
# Java VM: OpenJDK 64-Bit Server VM (23-internal-adhoc.daniel.jdk, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libasyncProfiler.so+0x6ecf]  NMethod::isNMethod()+0x1f
```

The crashes started after [this commit](https://github.com/openjdk/jdk/commit/b704e91241b0f84d866f50a8f2c6af240087cb29). I tried profiler versions 2.9 and 3.0, same crash in both cases. I'm using JMH to run the profiler.

**Comment by apangin** [comment] 2024-05-08 01:04
The problem is understood. I will prepare a fix soon.

**Comment by apangin** [comment] 2024-05-13 00:36
I pushed the fix, please check it if helps.
`cstack=vm` is still not fully supported on JDK 23, it will be fixed in a separate commit. Otherwise everything should work fine.

**Comment by djelinski** [comment] 2024-05-13 08:58
I checked the CI build and I can confirm that it fixes the crash on 23-ea.

**Closed** 2024-05-13 08:58 UTC
Labels: bug

**Comment by fmeum** [comment] 2024-09-19 20:25
Over at [Bazel](https://github.com/bazelbuild/bazel/pull/23651), which bundles async-profiler, we are trying to update to JDK 23, but face a similar crash to this one with 3.0. I checked that the nightly releases appear to work well, but we need stable (as in, SHA256 hash doesn't change) download locations. A minor release would be really helpful for us.

**Comment by alexander-yakushev** [comment] 2024-10-04 06:47
Another datapoint – https://github.com/clojure-goes-fast/clj-async-profiler crashes with the same error when on async-profiler 3.0 and JDK23. Nightly build appears to work well.

**Comment by ryantheleach** [comment] 2024-10-12 09:42
Thanks for fixing it, would it be possible to cut a release to fix this issue given the release of Java 23?

**Comment by apangin** [comment] 2024-10-12 12:18
@ryantheleach New release is being prepared. In the meantime, you may take a [pre-release version](https://github.com/async-profiler/async-profiler/releases/tag/nightly).

**Comment by apangin** [comment] 2025-01-23 17:40
@mr-git Answered [here](https://github.com/async-profiler/async-profiler/discussions/1057#discussioncomment-11315765)
