### ISSUE TITLE
asprof make jvm8 crashed, when JavaThread `Attach Listener` running

### ISSUE THREAD

**Issue by chacha923** [async-profiler/async-profiler#1063] opened 2024-11-26 09:06 UTC
### Describe the bug

hello, i use client-go and spdy library enter a java application container from an agent container, which at the same node of java container to execute asprof, but jvm crashed sometimes after a few seconds,  because a segment fault 
container exit code 137  and java process received a SIGSEGV signal

### Expected vs. actual behavior
I think JavaThread "Attach Listener"  may happened a exception; maybe make check_match function of ld-linux-x86-64.so.2  accessed a illegal memory address！

```bash
asprof command: ./asprof -d 60 -f xxx.html -e ctimer --all-user --fdtransfer

latest terminal log:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f54ae1d7570, pid=1, tid=0x00007f53a8430700
#
# JRE version: OpenJDK Runtime Environment (8.0_322-b06) (build 1.8.0_322-b06)
# Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0x9570]  check_match.9525+0x10
#
# Core dump written. Default location: /home/admin/core or core.1
#
# An error report file with more information is saved as:
# /home/admin/hs_err_pid1.log
2024-11-26 16:51:10.420 DEBUG [,] [DubboServerHandler-10.50.48.145:20880-thread-400] org.apache.dubbo.remoting.transport.DecodeHandler:59 -  [DUBBO] Decode decodeable message org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation, dubbo version: 1.2.11-SNAPSHOT, current host: 10.50.48.145
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=java-1.8.0-openjdk
#
Profiling started

[error occurred during error reporting , id 0xb]
...

[Too many errors, abort]
...

```

### Additional Information/Context

jvm error log of thread

```bash
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcc9f3c5570, pid=1, tid=0x00007fcb95b35700
#
# JRE version: OpenJDK Runtime Environment (8.0_322-b06) (build 1.8.0_322-b06)
# Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0x9570]  check_match.9525+0x10
#
# Core dump written. Default location: /home/admin/core or core.1
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=java-1.8.0-openjdk
#

---------------  T H R E A D  ---------------

Current thread (0x00007fcc18001000):  JavaThread "Attach Listener" daemon [_thread_in_vm, id=1168, stack(0x00007fcb95a35000,0x00007fcb95b36000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00000000000016bc

Registers:
RAX=0x0000000000000282, RBX=0x00007fcb95b33370, RCX=0x000000004fad5785, RDX=0x00007fcac119e298
RSP=0x00007fcb95b33300, RBP=0x00000000000016b8, RSI=0x0000000000000358, RDI=0x00000000000016b8
R8 =0x0000000000000005, R9 =0x00000000013eb55e, R10=0x00007fcb95b33370, R11=0x00007fcb95b33470
R12=0x0000000000000009, R13=0x000000004fad5785, R14=0x00007fcb58001460, R15=0x0000000000000000
RIP=0x00007fcc9f3c5570, EFLAGS=0x0000000000010206, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007fcb95b33300)
0x00007fcb95b33300:   00007fcb585f82fa 00000000000002a8
0x00007fcb95b33310:   0000000000000000 0000000000000009
0x00007fcb95b33320:   000000004fad5785 00007fcc9f3c5dbb
0x00007fcb95b33330:   0000000000000080 00007fcb95b33370
0x00007fcb95b33340:   00007fcac119e298 00000000013eb55e
0x00007fcb95b33350:   00007fcb95b33480 00007fcb95b33470
0x00007fcb95b33360:   00007fcb00000005 00007fcc9f3cb7d4
0x00007fcb95b33370:   0000000000000000 0000000000000000
0x00007fcb95b33380:   00007fcb58253450 00007fcb58265d90
0x00007fcb95b33390:   0000000000001700 0000000000000000
0x00007fcb95b333a0:   0000000200000000 00000000000000d6
0x00007fcb95b333b0:   0000000000000000 00007fcb95b33560
0x00007fcb95b333c0:   00007fcb95b33510 0000000000000000
0x00007fcb95b333d0:   0000000000000000 00007fcb582537d8
0x00007fcb95b333e0:   00007fcb58253450 00007fcc9f3c609f
0x00007fcb95b333f0:   0000000000000000 0000000000000000
0x00007fcb95b33400:   3e18196200000002 0000000000000000
0x00007fcb95b33410:   00007ffc00000000 00007fcb58253450
0x00007fcb95b33420:   00007fcb95b33600 00007fcb58000020
0x00007fcb95b33430:   00007fcb58000020 0000000000000000
0x00007fcb95b33440:   0000000000000007 00007fcb582537d8
0x00007fcb95b33450:   00007fcb95b33480 00007fcb95b33470
0x00007fcb95b33460:   000000004fad5785 00007fcb58265d90
0x00007fcb95b33470:   00000000ffffffff 0000000000000044
0x00007fcb95b33480:   0000000000000000 0000000000000000
0x00007fcb95b33490:   fffffffffffffffe 00007fcc9f3cfba6
0x00007fcb95b334a0:   0000007800000076 00007fcc9e03d652
0x00007fcb95b334b0:   00007fcb95b33400 0000000000000000
0x00007fcb95b334c0:   0000000000000000 00007fcb58250979
0x00007fcb95b334d0:   0000000080000001 00007fcc9e03d652
0x00007fcb95b334e0:   00007fcc9eb77fab 00007fcc9f5ddc00
0x00007fcb95b334f0:   00007fcc9f5de000 0000558ac720f510 

Instructions: (pc=0x00007fcc9f3c5570)
0x00007fcc9f3c5550:   77 fd ff ff 66 2e 0f 1f 84 00 00 00 00 00 66 90
0x00007fcc9f3c5560:   41 55 41 54 55 48 89 fd 53 4c 89 d3 48 83 ec 08
0x00007fcc9f3c5570:   0f b6 47 04 83 e0 0f 48 83 7f 08 00 0f 84 10 01
0x00007fcc9f3c5580:   00 00 31 d2 66 83 7d 06 00 0f 94 c2 85 53 3c 0f 

Register to memory mapping:

RAX=0x0000000000000282 is an unknown value
RBX=0x00007fcb95b33370 is pointing into the stack for thread: 0x00007fcc18001000
RCX=0x000000004fad5785 is an unknown value
RDX=
[error occurred during error reporting (printing register info), id 0xb]

Stack: [0x00007fcb95a35000,0x00007fcb95b36000],  sp=0x00007fcb95b33300,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ld-linux-x86-64.so.2+0x9570]  check_match.9525+0x10


---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00007fcbf800a000 JavaThread "Keep-Alive-Timer" daemon [_thread_blocked, id=1186, stack(0x00007fcb94531000,0x00007fcb94632000)]
  0x00007fcb5c06f800 JavaThread "nacos-grpc-client-executor-10.50.2.152-467" daemon [_thread_blocked, id=1185, stack(0x00007fcbef0db000,0x00007fcbef1dc000)]
  0x00007fcb5c047000 JavaThread "nacos-grpc-client-executor-10.50.2.152-466" daemon [_thread_blocked, id=1181, stack(0x00007fcb94430000,0x00007fcb94531000)]
=>0x00007fcc18001000 JavaThread "Attach Listener" daemon [_thread_in_vm, id=1168, stack(0x00007fcb95a35000,0x00007fcb95b36000)]
  0x00007fcb8c06d800 JavaThread "NettyServerWorker-5-1" daemon [_thread_in_native, id=169, stack(0x00007fcbeefda000,0x00007fcbef0db000)]
  0x00007fcc0800b800 JavaThread "prometheus-http-1-1" daemon [_thread_blocked, id=164, stack(0x00007fcb9432f000,0x00007fcb94430000)]
  0x00007fcc986e5800 JavaThread "ajp-nio-8009-AsyncTimeout" daemon [_thread_blocked, id=160, stack(0x00007fcac39fa000,0x00007fcac3afb000)]
  0x00007fcc986e3800 JavaThread "ajp-nio-8009-Acceptor-0" daemon [_thread_in_native, id=159, stack(0x00007fcac3afb000,0x00007fcac3bfc000)]
  0x00007fcc9854d000 JavaThread "ajp-nio-8009-ClientPoller-1" daemon [_thread_in_native, id=158, stack(0x00007fcac3bfc000,0x00007fcac3cfd000)]
  0x00007fcc9854b800 JavaThread "ajp-nio-8009-ClientPoller-0" daemon [_thread_in_native, id=157, stack(0x00007fcac3cfd000,0x00007fcac3dfe000)]
  0x00007fcc98549000 JavaThread "ajp-nio-8009-exec-10" daemon [_thread_blocked, id=156, stack(0x00007fcac3dfe000,0x00007fcac3eff000)]
  0x00007fcc98547000 JavaThread "ajp-nio-8009-exec-9" daemon [_thread_blocked, id=155, stack(0x00007fcac3eff000,0x00007fcac4000000)]
  0x00007fcc98543000 JavaThread "ajp-nio-8009-exec-8" daemon [_thread_blocked, id=154, stack(0x00007fcb54097000,0x00007fcb54198000)]
  0x00007fcc98541000 JavaThread "ajp-nio-8009-exec-7" daemon [_thread_blocked, id=153, stack(0x00007fcb54198000,0x00007fcb54299000)]
  0x00007fcc9853f000 JavaThread "ajp-nio-8009-exec-6" daemon [_thread_blocked, id=152, stack(0x00007fcb54299000,0x00007fcb5439a000)]
  0x00007fcc9853d000 JavaThread "ajp-nio-8009-exec-5" daemon [_thread_blocked, id=151, stack(0x00007fcb5439a000,0x00007fcb5449b000)]
  0x00007fcc98573800 JavaThread "ajp-nio-8009-exec-4" daemon [_thread_blocked, id=150, stack(0x00007fcb5449b000,0x00007fcb5459c000)]
  0x00007fcc98571800 JavaThread "ajp-nio-8009-exec-3" daemon [_thread_blocked, id=149, stack(0x00007fcb5459c000,0x00007fcb5469d000)]
  0x00007fcc9856f800 JavaThread "ajp-nio-8009-exec-2" daemon [_thread_blocked, id=148, stack(0x00007fcb5469d000,0x00007fcb5479e000)]
  0x00007fcc9856d800 JavaThread "ajp-nio-8009-exec-1" daemon [_thread_blocked, id=147, stack(0x00007fcb5479e000,0x00007fcb5489f000)]
  0x00007fcc987a7800 JavaThread "http-nio-8080-AsyncTimeout" daemon [_thread_blocked, id=146, stack(0x00007fcb5489f000,0x00007fcb549a0000)]
  0x00007fcc987a7000 JavaThread "http-nio-8080-Acceptor-0" daemon [_thread_in_native, id=145, stack(0x00007fcb549a0000,0x00007fcb54aa1000)]
  0x00007fcc987a4800 JavaThread "http-nio-8080-ClientPoller-1" daemon [_thread_in_native, id=144, stack(0x00007fcb54aa1000,0x00007fcb54ba2000)]
  0x00007fcc9892d000 JavaThread "http-nio-8080-ClientPoller-0" daemon [_thread_in_native, id=143, stack(0x00007fcb54ba2000,0x00007fcb54ca3000)]
  0x00007fcc98928800 JavaThread "http-nio-8080-exec-10" daemon [_thread_blocked, id=142, stack(0x00007fcb54ca3000,0x00007fcb54da4000)]
  0x00007fcc98927000 JavaThread "http-nio-8080-exec-9" daemon [_thread_blocked, id=141, stack(0x00007fcb54da4000,0x00007fcb54ea5000)]
  0x00007fcc98814000 JavaThread "http-nio-8080-exec-8" daemon [_thread_blocked, id=140, stack(0x00007fcb54ea5000,0x00007fcb54fa6000)]
  0x00007fcc98812800 JavaThread "http-nio-8080-exec-7" daemon [_thread_blocked, id=139, stack(0x00007fcb54fa6000,0x00007fcb550a7000)]
  0x00007fcc98810800 JavaThread "http-nio-8080-exec-6" daemon [_thread_blocked, id=138, stack(0x00007fcb550a7000,0x00007fcb551a8000)]
  0x00007fcc9880e800 JavaThread "http-nio-8080-exec-5" daemon [_thread_blocked, id=137, stack(0x00007fcb551a8000,0x00007fcb552a9000)]
  0x00007fcc986dd800 JavaThread "http-nio-8080-exec-4" daemon [_thread_blocked, id=136, stack(0x00007fcb552a9000,0x00007fcb553aa000)]
  0x00007fcc986dd000 JavaThread "http-nio-8080-exec-3" daemon [_thread_blocked, id=135, stack(0x00007fcbeebd6000,0x00007fcbeecd7000)]
  0x00007fcc986dc000 JavaThread "http-nio-8080-exec-2" daemon [_thread_blocked, id=134, stack(0x00007fcbeecd7000,0x00007fcbeedd8000)]
  0x00007fcc986e1000 JavaThread "http-nio-8080-exec-1" daemon [_thread_blocked, id=133, stack(0x00007fcbeedd8000,0x00007fcbeeed9000)]
  0x00007fcc985eb000 JavaThread "ContainerBackgroundProcessor[StandardEngine[Catalina]]" daemon [_thread_blocked, id=132, stack(0x00007fcbeeed9000,0x00007fcbeefda000)]
  0x00007fcbc3598800 JavaThread "metrics-reporter-4-t-1" [_thread_blocked, id=131, stack(0x00007fcb559a5000,0x00007fcb55aa6000)]
  0x00007fcbc359b000 JavaThread "heartbeat-reporter-3-t-1" [_thread_blocked, id=130, stack(0x00007fcb55aa6000,0x00007fcb55ba7000)]
  0x00007fcbc3516800 JavaThread "kafka-producer-network-thread | producer-1" daemon [_thread_in_native, id=129, stack(0x00007fcb55ba7000,0x00007fcb55ca8000)]
  0x00007fcbc33a9800 JavaThread "metrics-event-consumer-2-t-3" [_thread_blocked, id=128, stack(0x00007fcb555aa000,0x00007fcb556ab000)]
  0x00007fcbc33a6000 JavaThread "metrics-event-consumer-2-t-2" [_thread_blocked, id=127, stack(0x00007fcb556ab000,0x00007fcb557ac000)]
  0x00007fcbc33a5800 JavaThread "metrics-event-consumer-2-t-1" [_thread_blocked, id=126, stack(0x00007fcb557ac000,0x00007fcb558ad000)]
  0x00007fcbc336f000 JavaThread "trace-reporter-1-t-1" [_thread_blocked, id=125, stack(0x00007fcb56efe000,0x00007fcb56fff000)]
  0x00007fcbc3369000 JavaThread "Thread-25" daemon [_thread_in_native, id=124, stack(0x00007fcb9402c000,0x00007fcb9412d000)]
  0x00007fcbc334e000 JavaThread "server-timer" daemon [_thread_blocked, id=123, stack(0x00007fcb9412d000,0x00007fcb9422e000)]
  0x00007fcbc32c9800 JavaThread "pool-8-thread-1" [_thread_blocked, id=122, stack(0x00007fcb9422e000,0x00007fcb9432f000)]
  0x00007fcb5823d800 JavaThread "grpc-nio-worker-ELG-1-2" daemon [_thread_in_native, id=117, stack(0x00007fcb95734000,0x00007fcb95835000)]
  0x00007fcbc321b800 JavaThread "grpc-nio-worker-ELG-1-1" daemon [_thread_in_native, id=115, stack(0x00007fcb95b36000,0x00007fcb95c37000)]
  0x00007fcbc2c5a000 JavaThread "com.alibaba.nacos.client.remote.worker" daemon [_thread_blocked, id=114, stack(0x00007fcb96037000,0x00007fcb96138000)]
  0x00007fcbc2c58000 JavaThread "com.alibaba.nacos.client.remote.worker" daemon [_thread_blocked, id=113, stack(0x00007fcb96138000,0x00007fcb96239000)]
  0x00007fcbc2c50800 JavaThread "com.alibaba.nacos.client.naming.grpc.redo.0" daemon [_thread_blocked, id=112, stack(0x00007fcb96239000,0x00007fcb9633a000)]
  0x00007fcbc2bc3800 JavaThread "com.alibaba.nacos.naming.push.receiver" daemon [_thread_in_native, id=111, stack(0x00007fcb9653a000,0x00007fcb9663b000)]
  0x00007fcbc2bbf800 JavaThread "com.alibaba.nacos.client.naming.security" daemon [_thread_blocked, id=110, stack(0x00007fcb9663b000,0x00007fcb9673c000)]
  0x00007fcbc2bbd800 JavaThread "com.alibaba.nacos.client.auth.ram.identify.watcher.0" daemon [_thread_blocked, id=109, stack(0x00007fcb9673c000,0x00007fcb9683d000)]
  0x00007fcbc2b70000 JavaThread "com.alibaba.nacos.naming.failover" daemon [_thread_blocked, id=108, stack(0x00007fcb9683d000,0x00007fcb9693e000)]
  0x00007fcbc2b63800 JavaThread "nacos.publisher-com.alibaba.nacos.client.naming.event.InstancesChangeEvent" daemon [_thread_blocked, id=107, stack(0x00007fcb9693e000,0x00007fcb96a3f000)]
  0x00007fcbc2b56800 JavaThread "nacos.publisher-com.alibaba.nacos.common.notify.SlowEvent" daemon [_thread_blocked, id=106, stack(0x00007fcb96a3f000,0x00007fcb96b40000)]
  0x00007fcbc2ac0000 JavaThread "NettyServerBoss-4-1" daemon [_thread_in_native, id=105, stack(0x00007fcb96b40000,0x00007fcb96c41000)]
  0x00007fcbc2a69000 JavaThread "qos-boss-1-1" daemon [_thread_in_native, id=104, stack(0x00007fcb97cff000,0x00007fcb97e00000)]
  0x00007fcbc2686000 JavaThread "Dubbo-Access-Log-thread-1" daemon [_thread_blocked, id=101, stack(0x00007fcbec089000,0x00007fcbec18a000)]
  0x00007fcbc25a0800 JavaThread "Apollo-SpringValueRegistry-1" daemon [_thread_blocked, id=100, stack(0x00007fcbec18a000,0x00007fcbec28b000)]
  0x00007fcbc21f9800 JavaThread "pool-4-thread-1" [_thread_blocked, id=99, stack(0x00007fcbede33000,0x00007fcbedf34000)]
  0x00007fcbc13d3000 JavaThread "logback-12" daemon [_thread_blocked, id=82, stack(0x00007fcbee334000,0x00007fcbee435000)]
  0x00007fcbc13d2000 JavaThread "logback-11" daemon [_thread_blocked, id=81, stack(0x00007fcbee637000,0x00007fcbee738000)]
  0x00007fcbc0b7b000 JavaThread "logback-10" daemon [_thread_blocked, id=80, stack(0x00007fcbee839000,0x00007fcbee93a000)]
  0x00007fcbc0b7a800 JavaThread "logback-9" daemon [_thread_blocked, id=79, stack(0x00007fcbee435000,0x00007fcbee536000)]
  0x00007fcbc1392800 JavaThread "logback-8" daemon [_thread_blocked, id=78, stack(0x00007fcbee536000,0x00007fcbee637000)]
  0x00007fcbc0b7d000 JavaThread "logback-7" daemon [_thread_blocked, id=77, stack(0x00007fcbee738000,0x00007fcbee839000)]
  0x00007fcbc1368800 JavaThread "Apollo-RemoteConfigLongPollService-1" daemon [_thread_in_native, id=76, stack(0x00007fcbed48b000,0x00007fcbed58c000)]
  0x00007fcbc133f800 JavaThread "Apollo-RemoteConfigRepository-1" daemon [_thread_blocked, id=75, stack(0x00007fcbed58c000,0x00007fcbed68d000)]
  0x00007fcbc131b000 JavaThread "Apollo-ConfigServiceLocator-1" daemon [_thread_blocked, id=74, stack(0x00007fcbed932000,0x00007fcbeda33000)]
  0x00007fcc98adb800 JavaThread "NioBlockingSelector.BlockPoller-2" daemon [_thread_in_native, id=64, stack(0x00007fcbef3dc000,0x00007fcbef4dd000)]
  0x00007fcc98aaa800 JavaThread "NioBlockingSelector.BlockPoller-1" daemon [_thread_in_native, id=63, stack(0x00007fcbef4dd000,0x00007fcbef5de000)]
  0x00007fcc98999000 JavaThread "GC Daemon" daemon [_thread_blocked, id=62, stack(0x00007fcbef7fa000,0x00007fcbef8fb000)]
  0x00007fcc98531800 JavaThread "Service Thread" daemon [_thread_blocked, id=60, stack(0x00007fcbefbfc000,0x00007fcbefcfd000)]
  0x00007fcc9852f000 JavaThread "C1 CompilerThread1" daemon [_thread_blocked, id=59, stack(0x00007fcbefcfe000,0x00007fcbefdfe000)]
  0x00007fcc9852a800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=58, stack(0x00007fcbefdff000,0x00007fcbefeff000)]
  0x00007fcc98528800 JavaThread "JDWP Event Helper Thread" daemon [_thread_blocked, id=57, stack(0x00007fcbefeff000,0x00007fcbf0000000)]
  0x00007fcc984d5000 JavaThread "JDWP Transport Listener: dt_socket" daemon [_thread_in_native, id=56, stack(0x00007fcc398da000,0x00007fcc399db000)]
  0x00007fcc14a51000 JavaThread "SOUL_AGENT_THREAD-threads-analysis-reporter" daemon [_thread_blocked, id=54, stack(0x00007fcc382b1000,0x00007fcc383b2000)]
  0x00007fcc14a2f800 JavaThread "SOUL_AGENT_THREAD-APM-notify-thread" daemon [_thread_blocked, id=53, stack(0x00007fcc383b2000,0x00007fcc384b3000)]
  0x00007fcc149f9800 JavaThread "SOUL_AGENT_THREAD-kafka-producer-network-thread | soul-agent-trace-producer" daemon [_thread_in_native, id=51, stack(0x00007fcc384b3000,0x00007fcc385b4000)]
  0x00007fcc1480a800 JavaThread "SOUL_AGENT_THREAD-Apollo-RemoteConfigLongPollService-1" daemon [_thread_in_native, id=50, stack(0x00007fcc387b4000,0x00007fcc388b5000)]
  0x00007fcc14807000 JavaThread "SOUL_AGENT_THREAD-Apollo-RemoteConfigRepository-1" daemon [_thread_blocked, id=49, stack(0x00007fcc388b5000,0x00007fcc389b6000)]
  0x00007fcc147f0000 JavaThread "SOUL_AGENT_THREAD-Apollo-ConfigServiceLocator-1" daemon [_thread_blocked, id=48, stack(0x00007fcc389b6000,0x00007fcc38ab7000)]
  0x00007fcc14001000 JavaThread "Thread-4" daemon [_thread_in_native, id=45, stack(0x00007fcc397d9000,0x00007fcc398da000)]
  0x00007fcc984c2800 JavaThread "server-timer" daemon [_thread_blocked, id=43, stack(0x00007fcc399db000,0x00007fcc39adc000)]
  0x00007fcc983c3000 JavaThread "AsyncFileHandlerWriter-531885035" daemon [_thread_blocked, id=42, stack(0x00007fcc39ce6000,0x00007fcc39de7000)]
  0x00007fcc9826d800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=41, stack(0x00007fcc8030f000,0x00007fcc80410000)]
  0x00007fcc9826b800 JavaThread "Surrogate Locker Thread (Concurrent GC)" daemon [_thread_blocked, id=40, stack(0x00007fcc80410000,0x00007fcc80511000)]
  0x00007fcc98241000 JavaThread "Finalizer" daemon [_thread_blocked, id=39, stack(0x00007fcc80511000,0x00007fcc80612000)]
  0x00007fcc9823c000 JavaThread "Reference Handler" daemon [_thread_blocked, id=38, stack(0x00007fcc80612000,0x00007fcc80713000)]
  0x00007fcc98050800 JavaThread "main" [_thread_in_native, id=16, stack(0x00007fcc9f4d1000,0x00007fcc9f5d1000)]

Other Threads:
  0x00007fcc98232800 VMThread [stack: 0x00007fcc80714000,0x00007fcc80814000] [id=37]
  0x00007fcc98545000 WatcherThread [stack: 0x00007fcbefafc000,0x00007fcbefbfc000] [id=61]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

heap address: 0x00000000e0000000, size: 512 MB, Compressed Oops mode: 32-bit
Narrow klass base: 0x0000000000000000, Narrow klass shift: 3
Compressed class space size: 1073741824 Address: 0x0000000100000000




Memory: 4k page, physical 2097152k(338896k free), swap 0k(0k free)

vm_info: OpenJDK 64-Bit Server VM (25.322-b06) for linux-amd64 JRE (1.8.0_322-b06), built on Jan 27 2022 17:54:59 by "mockbuild" with gcc 4.8.5 20150623 (Red Hat 4.8.5-44)

time: Tue Nov 26 15:37:51 2024
timezone: CST
elapsed time: 2137.616160 seconds (0d 0h 35m 37s)

```

### Async-profiler version

Async-profiler 3.0 built on Jan 20 2024

### Environment details

OS:CentOS Linux release 7.9.2009 (Core)

JVM environment 
-XX:CICompilerCount=2 -XX:ConcGCThreads=6 -XX:ErrorFile=/home/admin/apache-tomcat-8.5.42/logs/hs_err_pid%p.log -XX:G1HeapRegionSize=1048576 -XX:InitialHeapSize=33554432 -XX:MarkStackSize=4194304 -XX:MaxHeapSize=536870912 -XX:MaxNewSize=321912832 -XX:MinHeapDeltaBytes=1048576 -XX:ParallelGCThreads=6 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseFastUnorderedTimeStamps -XX:+UseG1GC 

JRE version: OpenJDK Runtime Environment (8.0_322-b06) (build 1.8.0_322-b06)
Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)

CPU: amd64

**Comment by apangin** [comment] 2024-11-27 01:15
Thank you for the bug report. Do you have a full `hs_err.log`? You may send it privately to <support @ profiler.tools> if you wish.

I see that an application runs in a container. What is an OS inside a container? Also CentOS?

Also, can you check if the latest [nightly release](https://github.com/async-profiler/async-profiler/releases/tag/nightly) works?
Thanks.

**Comment by apangin** [comment] 2024-12-13 13:19
@chacha923 Did you check if the issue happens with nightly builds?

It's likely that the problem was caused by the fact that most of shared libraries (including `libjvm.so` and `libc.so`) were deleted while the application was running - note `(deleted)` in the crash dump.

**Comment by apangin** [comment] 2024-12-23 22:46
I'm closing the issue in the lack of further debugging details. The probem is apparently caused by external factors, such as deletion of shared libraries while an application is running.
Feel free to reopen if you have additional information on how to reproduce the issue.

**Closed by apangin** 2024-12-23 22:46 UTC
Labels: external
