### ISSUE TITLE
Profiler already started after write file failed

### ISSUE THREAD

**Issue by Jungzhang** [async-profiler/async-profiler#830] opened 2023-10-27 02:26 UTC
1. Start proflier task, specific -f to output file, but write file failed
2. Start new proflier task, Report an error "[ERROR] Profiler already started"

**Comment by apangin** [comment] 2023-10-27 10:07
I'm not sure I fully understand the question - what does "write file failed" exactly means? Does profiler print any error?
Could you share the exact commands you type and all profiler messages?

**Comment by apangin** [comment] 2023-10-27 10:08
`[ERROR] Profiler already started` message means the profiler is still running. You can stop it with the `stop` command along with `-f` option to dump results in the given file.

**Comment by Jungzhang** [comment] 2023-10-28 08:46
Thank you for your reply.

 I use `./profiler.sh -d 3 -f /root/profil.html` start a profiler task, write failed because the process does not have write permission to the /root directory. I restart `./profiler.sh -d 3 -f /root/profil.html` print `[ERROR] Profiler already started`.

**Comment by apangin** [comment] 2023-10-28 10:01
This is the intended behavior, I don't see an issue here.

If stopping fails (because of permissions or something), profiler keeps running to allow a user to stop it correctly and dump results to a different file.

I'm closing the issue as a duplicate of #699.

**Closed by apangin** 2023-10-28 10:01 UTC
