### ISSUE TITLE
Async-Profiler connectivity issue with Java Pods in K8s cluster to enable profiling

### ISSUE THREAD

**Issue by Vaibhav-1995** [async-profiler/async-profiler#1067] opened 2024-11-29 09:46 UTC
### Describe the bug

I am using Java Profiling with Alloy (auto-instrumentation method) for enabling profiling on java pods wthin cluster. Deployed pyroscope and alloy separately using helm chart and have added below config in alloy configmap for java profiling as provided on below link - 
https://github.com/grafana/pyroscope/tree/main/examples/grafana-agent-auto-instrumentation/java/kubernetes

    content:  |

      logging {
        level  = "debug"
        format = "logfmt"
      }

      // Discovers all kubernetes pods.
      // Relies on serviceAccountName=grafana-alloy in the pod spec for permissions.
      discovery.kubernetes "pods" {
        role = "pod"
      }

      // Discovers all processes running on the node.
      // Relies on a security context with elevated permissions for the alloy container (running as root).
      // Relies on hostPID=true on the pod spec, to be able to see processes from other pods.
      discovery.process "all" {
        // Merges kubernetes and process data (using container_id), to attach kubernetes labels to discovered processes.
        join = discovery.kubernetes.pods.targets
      }
      // Drops non-java processes and adjusts labels.    
      discovery.relabel "java" {
        targets = discovery.process.all.targets
        // Drops non-java processes.
        rule {
          source_labels = ["__meta_process_exe"]
          action = "keep"
          regex = ".*/java$"
        }
        // Sets up the service_name using the namespace and container names.
        rule {
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
          target_label = "service_name"
          separator = "/"
        }
        // Sets up kubernetes labels (labels with the __ prefix are ultimately dropped).
        rule {
          action = "replace"
          source_labels = ["__meta_kubernetes_pod_node_name"]
          target_label = "node"
        }
        rule {
          action = "replace"
          source_labels = ["__meta_kubernetes_namespace"]
          target_label = "namespace"
        }
        rule {
          action = "replace"
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label = "pod"
        }
        rule {
          action = "replace"
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label = "container"
        }
        // Sets up the cluster label.
        // Relies on a pod-level annotation with the "cluster_name" name.
        // Alternatively it can be set up using external_labels in pyroscope.write. 
        rule {
          action = "replace"
          source_labels = ["__meta_kubernetes_pod_annotation_cluster_name"]
          target_label = "cluster"
        }
      }

      // Attaches the Pyroscope profiler to the processes returned by the discovery.relabel component.
      // Relies on a security context with elevated permissions for the alloy container (running as root).
      // Relies on hostPID=true on the pod spec, to be able to access processes from other pods.
      pyroscope.java "java" {
        profiling_config {
          interval = "15s"
          alloc = "512k"
          cpu = true
          lock = "10ms"
          sample_rate = 100
        }
        forward_to = [pyroscope.write.local.receiver]
        targets = discovery.relabel.java.output
      }
        
      pyroscope.write "local" {
        // Send metrics to the locally running Pyroscope instance.
        endpoint {
          url = "http://xxx-xxx-pyroscope-distributor.observability-pyroscope-dev.svc.cluster.local:4040"
        }
        external_labels = {
          "static_label" = "static_label_value",
        }
      }

But profiling starts on only few random java pods and seems issue with the async-profiler connectivity with all java pods. Not able to identify that why profiling is not enabled on all java pods as async-profiler works in backend 

### Expected vs. actual behavior

As per documentation on below link all pre-requisites are done at alloy end in helm chart - so not seems issue from alloy end as some pods starts profiling as well and that data is visible in grafana
https://grafana.com/docs/alloy/latest/reference/components/pyroscope/pyroscope.java/

### Async-profiler version

unknown-  as it is used in backend by alloy

### Environment details

OS- Linux
JDK- 17
EKS
Helm 
Argocd

**Comment by apangin** [comment] 2024-11-29 11:10
How did _async-profiler_ and _connectivity_ appear in the same sentence? Async-profiler is a tool that runs locally, it does not connect anywhere and it does not accept connections from outside.

For issues related to pyroscope configuration, please open a ticket against pyroscope instead.
Thanks.

**Comment by Vaibhav-1995** [comment] 2024-11-29 11:23
Ok @apangin 
Thanks for your quick reply.

But I am not able to understand why profiling is not getting started in all pods? And if issue persists in Pyroscope config I would have not received profiling data for some pods in grafana via Pyroscope datasource.

**Comment by apangin** [comment] 2024-11-29 15:33
Can you reproduce the issue using standalone async-profiler without Pyroscope?

**Comment by Vaibhav-1995** [comment] 2024-12-02 05:01
Hi @apangin 

Just want to clear one thing that in my setup **Pyroscope** is acting only as datasource. I have deployed separate (individual) helm charts for Pyroscope and Alloy.  So, I don't thing any issue at pyroscope end. Actual config of **pyroscope.java** lies in alloy chart under configmap from where it uses internally async-profiler (refer below link)
https://github.com/grafana/pyroscope/tree/main/examples/grafana-agent-auto-instrumentation/java/kubernetes

Below is one error log in alloy pod - 
**ts=2024-12-02T04:58:02.01712108Z level=error component_path=/ component_id=pyroscope.java.java pid=716979 err="failed to start: asprof failed to run: asprof failed to run /tmp/alloy-asprof-glibc-ed25bbf0083bff602254601eb6c4a927823d988f/bin/asprof: exit status 255  Target JVM failed to load /tmp/alloy-asprof-glibc-ed25bbf0083bff602254601eb6c4a927823d988f/bin/../lib/libasyncProfiler.so\n"**

**Comment by apangin** [comment] 2024-12-02 11:45
Thank you for the clarification. I would also like to clarify that async-profiler is an independent project, it does not provide support for Alloy, Pyroscope, Grafana, etc. If you are using async-profiler as a part of these products, please contact Grafana Labs instead. I'll therefore close this issue as external. Feel free to reopen or file a new issue if you have evidence that the problem is in standalone async-profiler. Thanks.

**Closed by apangin** 2024-12-02 11:45 UTC
Labels: external
