### ISSUE TITLE
Segfault on start when native mode profiling

### ISSUE THREAD

**Issue by abextm** [async-profiler/async-profiler#841] opened 2023-11-11 02:33 UTC
Using 6ab9f83aec0e4d216d3a5b911a6123db6139c544
Running `LD_PRELOAD=libasyncProfiler.so glxgears` segfaults immediately. This is because something else (`libglvnd` in this case) is calling `dlopen` before ld calls libasyncProfiler's init, so `Profiler::_instance` is null.

Adding this to the top of libasyncProfiler's `dlopen` works in this case, though I am unsure how correct this solution is.
```cpp
    if (Profiler::instance() == NULL) {
        return ((dlopen_t)dlsym(RTLD_NEXT, "dlopen"))(filename, flags);
    }
```

**Comment by apangin** [comment] 2023-11-21 15:30
I cannot reproduce the segfault.

Could you please elaborate on how profiler code is run before the library constructors are called?
What OS and architecture do you use? How do you build the profiler?

**Comment by abextm** [comment] 2023-11-21 19:32
I am on Arch amd64. I built the profiler by just running `make`.

I have attached a minimal C program & library that can reproduce this.

[asprof-841-repro.zip](https://github.com/async-profiler/async-profiler/files/13430278/asprof-841-repro.zip)

Compile with `./build.sh`, run with `LD_PRELOAD=path/to/libasyncProfiler.so LD_LIBRARY_PATH=. ./a.out`

**Comment by apangin** [comment] 2024-01-02 00:02
I pushed the fix. Please try if it resolves the issue.

**Closed** 2024-01-03 02:25 UTC
Labels: bug
