### ISSUE TITLE
How to write SocketSample in src/converter/one/jfr/event/

### ISSUE THREAD

**Issue by RaymondLam1** [async-profiler/async-profiler#716] opened 2023-02-22 09:09 UTC
* When I learn how to visualize socketsample, I don't know what does `sameGroup` function mean ? 
* For example, `jdk.SocketRead`, I would like to ask how to write its `sameGroup` function. Thank you so much!
<img width="958" alt="image" src="https://user-images.githubusercontent.com/96219320/220573488-9ea38d79-fe26-441c-86bf-fac11e77c2ba.png">

**Comment by RaymondLam1** [comment] 2023-02-22 11:57
* And I try to write `SocketSample.java`, however I get `Invalid string encoding`
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/96219320/220613318-27f6a534-fe09-4d3e-8d7f-0ce74edf5f43.png">

It seems to be right, I don't why it could not work. I wonderful your help.

**Comment by apangin** [comment] 2023-02-22 23:12
`sameGroup` method determines whether two events should be merged together during aggregation.
How to implement it depends on how do you want to see events grouped. Think of it as of `GROUP BY` clause in an SQL statement: include those fields in the comparison that you would add in `GROUP BY`.

**Comment by apangin** [comment] 2023-02-22 23:26
> It seems to be right, I don't why it could not work.

I can't say why it does not work too, due to lack of details about the entire code, input file and other essential setup required to reproduce the problem.
In any case, I will be happy to investigate issues in async-profiler, but you seem to ask about your own code written for your own purposes.

**Comment by RaymondLam1** [comment] 2023-02-23 00:47
* Glad to hear from you. I searched for information about the jfr file format and found a great article, I hope it will be useful to everyone[https://www.morling.dev/blog/jdk-flight-recorder-file-format/](https://www.morling.dev/blog/jdk-flight-recorder-file-format/)

**Comment by RaymondLam1** [comment] 2023-02-23 03:00
* I find it will work for me. Perhaps, `Constant Pool Reference` skip due to `getVarint()`. I try to open my jfr file in Oracle JMC 8.3, `Remote Host` is null which lead to `Invalid string encoding`. Maybe it is difficult to get what `Constant Pool Reference` mean.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/96219320/220810358-eaed0f96-9f59-4a5e-afff-e29ab153d54d.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/96219320/220810836-722bf44e-58d7-4921-9732-12563c8c339c.png">

* Maybe it is better to add  `case 2`  in `JfrReader.java`, I will continue to verify the conclusion. 
* PS It is my honor to communicate with you apangin. I am your fan and Aysnc-profiler is so excellent.

**Comment by apangin** [comment] 2023-03-30 21:39
Closing the issue as there is nothing to do on async-profiler end at this point.

**Closed by apangin** 2023-03-30 21:39 UTC
Labels: question, external

**Comment by qsLI** [comment] 2024-05-31 03:22
> Closing the issue as there is nothing to do on async-profiler end at this point.

String field encoding 2 stands for StringPool Item. When string length is between 16 and 128, jfr will try to use String pool cache to store it.

```java
// jdk.jfr.internal.EventWriter#putString
  public void putString(String s, StringPool pool) {
      if (s == null) {
          putByte(RecordingInput.STRING_ENCODING_NULL);
          return;
      }
      int length = s.length();
      if (length == 0) {
          putByte(RecordingInput.STRING_ENCODING_EMPTY_STRING);
          return;
      }
      if (length > StringPool.MIN_LIMIT && length < StringPool.MAX_LIMIT) {
          long l = StringPool.addString(s);
          if (l > 0) {
             // public static final byte STRING_ENCODING_CONSTANT_POOL = 2;
              putByte(RecordingInput.STRING_ENCODING_CONSTANT_POOL);
             // StringPool  index
              putLong(l);
              return;
          }
      }
      putStringValue(s);
      return;
  }
```

String pool write:
```cpp
// src/hotspot/share/jfr/recorder/stringpool/jfrStringPool.cpp
jboolean JfrStringPool::add(jlong id, jstring string, JavaThread* jt) {
  assert(jt != NULL, "invariant");
  {
    JfrStringPoolWriter writer(jt);
   // jlong
    writer.write(id);
    writer.write(string);
    writer.inc_nof_strings();
  }
  _new_string.signal();
  return JNI_TRUE;
}
```


## workaround

We can collect `java.lang.String`  JfrClass type，mapping StringPool id and real string.

```java
private void readConstants(JfrClass type) {
      switch (type.name) {
          case "jdk.types.ChunkHeader":
              buf.position(buf.position() + (CHUNK_HEADER_SIZE + 3));
              break;
          case "java.lang.Thread":
              readThreads(type.field("group") != null);
              break;
          case "java.lang.Class":
              readClasses(type.field("hidden") != null);
              break;
          case "jdk.types.Symbol":
              readSymbols();
              break;
          case "jdk.types.Method":
              readMethods();
              break;
          case "jdk.types.StackTrace":
              readStackTraces();
              break;
          case "jdk.types.FrameType":
              readMap(frameTypes);
              break;
          case "jdk.types.ThreadState":
              readMap(threadStates);
              break;
          case "java.lang.String":
              readLongMap(stringPool);
              break;
          default:
              readOtherConstants(type.fields);
      }
  }

  private void readLongMap(Map<Long, String> map) {
      Long count = getVarlong();
      for (long i = 0; i < count; i++) {
          map.put(getVarlong(), getString());
      }
  }
```

We can referer the stringPool map, when we ecounter a `2` encoding type:
```java
// one.jfr.JfrReader#getString
case 2:
      // String Pool
      final long itemId = getVarlong();
      return stringPool.get(itemId);
```
