### ISSUE TITLE
Crash inside ElfParser::ElfParser

### ISSUE THREAD

**Issue by zuevmaxim** [async-profiler/async-profiler#843] opened 2023-11-21 11:56 UTC
Crash appeared during native libraries parsing:
[java_error_in_idea_31063.log](https://github.com/async-profiler/async-profiler/files/13425883/java_error_in_idea_31063.log)

```addr2line -e libasyncProfiler.so -f -C -a 0x63203```
outputs
`ElfParser::ElfParser(CodeCache*, char const*, void const*, char const*, bool) at src/symbols_linux.cpp:152`
https://github.com/async-profiler/async-profiler/blob/6ab9f83aec0e4d216d3a5b911a6123db6139c544/src/symbols_linux.cpp#L152

I've added logs on each library parsing, so I can say that the crash appeared during `libproxy.so` parsing
[async-intellij_commit-20231120200326.log](https://github.com/async-profiler/async-profiler/files/13425886/async-intellij_commit-20231120200326.log)

**Comment by apangin** [comment] 2023-11-21 14:34
Thank you for the detailed report. I have a hypothesis about possible cause, let me check it.

**Comment by r1viollet** [comment] 2024-08-07 08:09
:wave: A similar crash was reported to Datadog. My assumption is that the mapping is no longer available at the time of parsing. So this would be a race between parsing the libraries and the unmapping of the associated mapping. I am able to crash the parsing code in this exact location by doing so.

Here is my proposal:
https://github.com/DataDog/java-profiler/pull/121/files

Happy to get feedback on whether this matches your assumption.

**Comment by apangin** [comment] 2024-08-08 21:42
@r1viollet Thank you for bringing this to our attention.
My understanding of the root cause was the same: concurrent unloading of a library during parsing.
I also thought about crash-protected read of ELF header, but this does not seem reliable: first, it reduces a chance of a crash, but does not eliminate it entirely; second, because OpenJ9 VM is not tolerant to altering SIGSEGV handler.

A better approach would be to use `dl_iterate_phdr` instead of scanning `/proc/self/maps` manually, but last time I tried it, I faced multiple issues and finally gave up. Now I think of a hybrid approach: call `dl_iterate_phdr` just to acquire dlopen/dlclose lock, and do manual scanning of `maps` inside the lock.

**Comment by r1viollet** [comment] 2024-08-09 07:31
Thank you for the feedback. I agree that I did not protect all the places that would be required to reach a 0 crash situation. However from what I see, this reduces the opening for the race from milliseconds to microseconds. So it might still be worth shipping.

**OpenJ9 topic:** 
Is it even an issue to replace the segv handler for the duration of the `parseLibraries` function ?
I would assume that at startup we are not too worried of the JVM relying on the segv handler. Or is this to design a `parseLibraries` function that could be called anytime?

**Topic around dl_iterate_solution:**
Grabbing the lock is interesting! In other runtimes (not Java), we have been worried about forking at such times, though this should not be an issue here. I assume you would write a callback that waits for the `parseLibraries` function to be finished to keep the lock.

**Comment by apangin** [comment] 2024-08-12 01:23
@r1viollet `parseLibraries` is called at the first attach to the JVM (when it can be in the middle of running an application) or at any time later whenever a new dynamic library is loaded. Anyhow, if you care only about the first access to a mapped region, you don't need to fiddle with signal handlers - it's easier (and safer) to call [`dladdr(base)`](https://man7.org/linux/man-pages/man3/dladdr.3.html) to verify that the mapping is still valid and belongs to the library being parsed.
Alternatively, you could call `dlopen(path, RTLD_LAZY | RTLD_NOLOAD)` before parsing to increment reference counter for the shared object, but it will not work for libraries whose backing file was removed from the file system.

Both approaches are not 100% reliable, therefore I decided to [proceed](https://github.com/async-profiler/async-profiler/commit/76311145c8fab34aab5e30e889d031f9ab23bf49) with `dl_iterate_phdr` solution.

Here is a [test](https://gist.github.com/apangin/5554a85ba5e98b466d49dce15049e302) I used for experiments.

**Comment by apangin** [comment] 2024-08-12 01:28
@zuevmaxim @MaXal I pushed the fix. Would love to hear back if it solves the problem you observed.

**Comment by r1viollet** [comment] 2024-08-12 08:00
This is indeed better. Thanks for looking into it.
Minor question: Would there be any reason to use the actual iteration mechanism and content of `dl_phdr_info` rather than re-parsing proc maps?

**Comment by apangin** [comment] 2024-08-12 13:38
> Would there be any reason to use the actual iteration mechanism and content of dl_phdr_info rather than re-parsing proc maps?

In theory, `dl_iterate` approach should be more reliable since it lists only real shared objects and does not require messing with virtual memory mappings. Unfortunately, implementation of `dl_iterate` varies much from system to system and has many peculiarities - I was not able to make it fully working. The prototype is available in [`dl-iterate`](https://github.com/async-profiler/async-profiler/tree/dl-iterate) branch. I'd love to see if someone can take this to completion.

**Closed** 2024-08-22 12:25 UTC
Labels: bug
