### ISSUE TITLE
Segmentation fault on Azul Zing

### ISSUE THREAD

**Issue by 70data** [async-profiler/async-profiler#934] opened 2024-05-22 09:48 UTC
We're using async-profiler.
Frequent JVM crashes with Segmentation fault.

async-profile: v3.0
Java VM: Zing 64-Bit Tiered VM (1.8.0_322-zing_22.02.0.0-b3-product-linux-X86_64, mixed mode)
Command: `./asprof --cstack dwarf -d 30 -f a.html pid`

[hs_err_pid.log](https://github.com/async-profiler/async-profiler/files/15401355/hs_err_pid.log)

We tried to follow the answer of the issue, but it didn't work.
https://github.com/async-profiler/async-profiler/issues/916

**Comment by apangin** [comment] 2024-05-23 01:37
According to `hs_err_pid.log`, the crash happened in a native thread not managed by the JVM, however, the thread somehow pointed back to `VMThread` structure.

I could not reproduce the crash myself, but I pushed a change that should fix the issue. Please verify if it helps.

**Comment by 70data** [comment] 2024-05-23 03:37
The whole call, which involves some interaction between JNI and so, may have similar problems.
Can you point out the approximate call location in `hs_err_pid.log` and we can help confirm it.

**Comment by apangin** [comment] 2024-05-23 10:27
Sorry, I'm not sure what call you are referring to. In any case, if the JVM no longer crashes or still crashes after the fix, please let me know. Thanks.

**Comment by 70data** [comment] 2024-05-23 11:42
In fact, I would like to ask how to confirm this reason.
> the crash happened in a native thread not managed by the JVM, however, the thread somehow pointed back to VMThread structure.

No problem. We'll test it and get back to you as soon as possible. Thanks.

**Comment by perrynzhou** [comment] 2024-05-29 06:27
@apangin hello,i has a problem，is that release?

**Comment by apangin** [comment] 2024-05-29 23:41
@perrynzhou The fix has been pushed and will get in the next release.
In the mean time, you can [build](https://github.com/async-profiler/async-profiler?tab=readme-ov-file#building) the project yourself or use the following prebuild binaries: 
[async-profiler-3.0-34a9e135-linux-x64.tar.gz](https://github.com/async-profiler/async-profiler/files/15491801/async-profiler-3.0-34a9e135-linux-x64.tar.gz)

**Comment by apangin** [comment] 2024-06-12 23:33
Closing the issue as resolved. Feel free to reopen if the fix does not work for you.

**Closed by apangin** 2024-06-12 23:33 UTC
Labels: bug

**Comment by 70data** [comment] 2024-06-24 12:31
I'm sorry for not getting back to you sooner.
After extensive testing, we have confirmed that the issue has been fixed.
Great job!

**Comment by wangyummm888** [comment] 2024-08-23 06:56
We used the newly provided fix version(https://profiler.tools/builds/async-profiler-3.0-34a9e135-linux-x64.tar.gz) to solve the frequent JVM crashes, but it caused a new problem where thread names were truncated in the generated HTML

For example, the correct thread name is CounterEngine-9-19, but the new version changes it to CounterEngine-9, causing truncation
![screenshot-20240823-144448](https://github.com/user-attachments/assets/31860187-d0a7-4fcc-a801-535dddd75915)
![screenshot-20240823-144728](https://github.com/user-attachments/assets/b8cf7a60-26dc-41d1-8d74-2b043b2c3160)

We tried to solve this issue by using options , but it didn't work

**Comment by apangin** [comment] 2024-08-23 09:28
@wangyummm888 Yes, this is a downside of the fix: since Java thread to platform thread mapping in Zing JVM is not reliable, async-profiler no longer uses it, therefore profiler cannot show full name of a Java thread and shows only a name of a platform thread which is limited to 15 characters on Linux.

Without a reproducer for the original crash, I don't have much space for experimenting with the fix. If you have a test cases that reproduces the crash, I'll be happy to continue my research.

**Comment by apangin** [comment] 2024-10-28 15:59
@lige955 The crash has been already resolved. You may verify this by using a [nightly release](https://github.com/async-profiler/async-profiler/releases/tag/nightly). If you still observe issues with the recent build, please submit a new bug report.
