### ISSUE TITLE
java.lang.NoSuchMethodError when calling jfr2flame with jdk 8

### ISSUE THREAD

**Issue by maozhu1123** [async-profiler/async-profiler#839] opened 2023-11-09 07:13 UTC
Environment: async-profiler v2.9 & jdk 8

```
> java -cp converter.jar jfr2flame --cpu java_profile.jfr test.html
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at one.jfr.JfrReader.<init>(JfrReader.java:78)
        at jfr2flame.main(jfr2flame.java:257)

> java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

```

**Comment by apangin** [comment] 2023-11-09 09:41
The problem is known and has been fixed already. I'm closing the issue as a duplicate of #772

**Closed by apangin** 2023-11-09 09:41 UTC
Labels: duplicate
