### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by oehme** [async-profiler/async-profiler#188] opened 2019-01-01 15:02 UTC
I don't know how feasible/hard it would be, but a lot of people are on Windows and would surely appreciate support for their platform. For me it's mostly about getting profiler snapshots from people using Gradle (the tool I work on) and most of our users are on Windows.

**Comment by apangin** [comment] 2019-01-04 17:14
I am a Windows user myself, and I would love to have a profiler with an equivalent functionality. However, I don't see how async-profiler can support Windows with a reasonable amount of effort. The problem is Windows does not have a concept of POSIX signals nor API similar to perf_event_open in Linux.

In theory it is possible to create an alternative profiling engine for Windows, but this would require introducing a new platform abstraction layer, reimplementing much of the existing code using Windows API, and maintaining all this stuff in future. Currently I'm not ready to sign up for this job myself, but I'll be glad to accept contributions if someone wishes to support async-profiler on Windows.

**Comment by imanushin** [comment] 2019-06-14 11:08
@apangin, can [Performance Counters](https://docs.microsoft.com/en-us/windows/desktop/perfctrs/performance-counters-portal) be alternative?

**Comment by apangin** [comment] 2019-06-14 23:04
@imanushin No, it's an unrelated technology.
In fact, the problem is not in the technology. It *is* possible to create a similar tool for Windows, but it will use quite different mechanism. Also, since Windows is not POSIX, the major part of the project will need to be rewritten: threads, timers, signals, I/O - all that stuff.

**Comment by mjsabby** [comment] 2020-02-19 10:13
For profiling to work on Windows, the JVM would need to report the unwind info to Windows.

For dynamically generated code, this is done using [RtlAddGrowableFunctionTable](https://docs.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-rtladdgrowablefunctiontable)

If `JVMTI` has access to the info that the JVM machine code emitter produces or can figure it out somehow, maybe by inspecting the machine code or because frame pointers are enabled, etc. it could report this to Windows and then the OS ETW Stack Walker will be able to walk the stack.

Ideally someone would fix the JVM to do this on Windows all the time, or at least when profiling is enabled (however that is determined in the JVM of choice) then extra machinery will not be needed.

For reference on how to do this in this tool or in the JVM, one could follow this commit that does essentially this for V8:

https://github.com/v8/v8/blob/3cda21de77d098a612eadf44d504b188a599c5f0/src/unwinding-info-win64.cc

**Comment by dunnry** [comment] 2020-03-06 17:30
Would the Windows Subsystem for Linux (WSL or WSL2) be an option here?  It's a full Linux kernel in the latter case.

**Comment by KirillTim** [comment] 2020-03-06 18:17
Just FYI, I do some work to port async-profiler on Windows. However, no time estimates or even working prototype yet.

**Comment by mjsabby** [comment] 2020-03-09 03:08
How are you porting it? Will you be reporting the ranges to Windows as I described above? That work will be great to also have in the JVM so everyone can benefit.

**Comment by mark4z** [comment] 2021-05-31 09:55
any update?

**Comment by TarasTielkes** [comment] 2021-05-31 16:20
The recent 2021.2 EAP release of IDEA seems to contain an initial release.
I was able to profile on AdoptOpenJDK 11, but not on 8.

**Comment by gorrus** [comment] 2021-06-07 16:59
@TarasTielkes yes, it is announced in EAP2: https://blog.jetbrains.com/idea/2021/06/intellij-idea-2021-2-eap-2/#profiler
Please give it a try!

**Comment by TarasTielkes** [comment] 2021-06-07 17:03
@gorrus way ahead of you :) I've been eagerly awaiting this for the last months, after watching the presentation by @KirillTim 
Since our main products are all still bound to Java 8, https://youtrack.jetbrains.com/issue/IDEA-270240 is my main impediment towards using it in daily work

**Comment by wolfs** [comment] 2021-06-09 10:12
Is there a way to try out async profiler for Windows without using IDEA?

**Comment by oehme** [comment] 2021-06-09 12:01
@wolfs JetBrains fork is here: https://github.com/JetBrains/async-profiler

**Comment by apangin** [comment] 2023-12-03 01:40
Creating and maintaining Windows port of async-profiler is a huge effort measured in man-years. Even though it is a desired feature among end users, there was hardly any demand for it from business so far (except maybe JetBrains who develop their own Windows port of the profiler).

I must admit Windows port is not currently on our roadmap, so I'm inclined to close the issue as not planned. I might bring it up again if the situation changes.

As a side note, with the introduction of [AsyncGetCallTrace replacement](https://github.com/async-profiler/async-profiler/issues/795) (`--cstack vm`), implementing proper stack walking on Windows became feasible, however, there are still many other things to be rewritten in order to support Java profiling on Windows.

**Closed by apangin** 2023-12-03 01:40 UTC
Labels: enhancement, wontfix

**Comment by Chris2011** [comment] 2024-09-15 14:11
Just an idea, what about lookin into the profiler of Chrome? This is working for WIndows too. Yes, I know it is just for JS but it looks into memory, cpu and chromium is open source. If this is a dumb Idea, just ignore the comment :D. I also had a look whether the profiler of IntellliJ is open source, but I just found this plugin, but is is obvious related to IntelliJ IDEA: https://github.com/parttimenerd/intellij-profiler-plugin. I was coming over to this ticket here of using a profiler in NetBeans, which was linked to this repo.

**Comment by kings1990** [comment] 2025-01-23 08:23
> [@wolfs](https://github.com/wolfs) JetBrains fork is here: https://github.com/JetBrains/async-profiler. Looks like the actual Windows parts are closed source.

It return 404
