### ISSUE TITLE
A thread was blocked at two objects multi times at the same time in Java Monitor Blocked event

### ISSUE THREAD

**Issue by qsLI** [async-profiler/async-profiler#659] opened 2022-10-20 07:00 UTC
As the picture shows， http-nio-21066-exec-386 thread was blocked at monitor address 0x385C1B410 and 0x2E83DB5A8，and the start time and end time is almost same. And there are four events related to 0x2E83DB5A8, with same start and end time. Is that possible？

![image](https://user-images.githubusercontent.com/6805785/196875948-a6d96991-a251-4aa7-bba2-6a7b38de4063.png)

**Comment by apangin** [comment] 2022-10-20 10:49
What was the version of JDK and the command for starting profiler?

**Comment by qsLI** [comment] 2022-10-21 09:32
> What was the version of JDK and the command for starting profiler?

version (internal patched version):   JAVA_VERSION  11.0.1  
command:   start,event=cpu,alloc=1m,lock=10ms,interval=10ms,jfrsync=/tmp/k.jfc,jfr=7,file=/tmp/profile1666343400004.jfr
CentOS Linux release 7.2.1511 (Core)
uname:Linux 4.18.0-2.4.3.kwai.x86_64 #1 SMP Fri Apr 23 14:40:10 CST 2021 x86_64
libc:glibc 2.17 NPTL 2.17
java.vm.name                  	OpenJDK 64-Bit Server VM

Using java api in-process profling.

**Comment by apangin** [comment] 2022-10-21 12:10
This does not look normal.
Is there a reliable way to reproduce the issue?

**Comment by qsLI** [comment] 2022-10-24 02:33
Currently, no stable way to reproduce. 
We use async profiler in jfrsync mode continuously monitor our app performance，the blocking happens occasionally.

**Comment by apangin** [comment] 2024-10-26 22:35
Haven't seen this problem so far, and there were no other reports.
I'll close the issue as outdated.
Feel free to reopen if the problem is still relevant and you have more information on how to reproduce it.

**Closed by apangin** 2024-10-26 22:35 UTC
Labels: outdated
