### ISSUE TITLE
AsyncProfiler Java API crashes the JVM

### ISSUE THREAD

**Issue by omarmahamid** [async-profiler/async-profiler#865] opened 2023-12-12 19:52 UTC
Hi, 

I'm using this peace of code (which is Java API for Async Profiler)

````
<dependency>
            <groupId>tools.profiler</groupId>
            <artifactId>async-profiler</artifactId>
            <version>2.9</version>
        </dependency>
````

````
        AsyncProfiler profiler = AsyncProfiler.getInstance();

        // Start profiling
        profiler.execute("start,event=cpu,file=startup-cpu-profile.html,interval=1000000,simple");

        // Code to be profiled
        Set<String> set = new HashSet<>();
        long start = System.currentTimeMillis();
        for (int i = 0; i < 100000000; i++) {
            boolean in = set.contains(String.valueOf(i).toUpperCase());
            BigDecimal bigDecimal = new BigDecimal("-21.2");
            bigDecimal.divide(new BigDecimal("-213.22"));
        }
        System.out.println("took: " + (System.currentTimeMillis() - start));

        Thread.sleep(10000);

        // Stop profiling
        profiler.execute("stop,file=startup-cpu-profile.html");

````

and I got that the JVM crash 

[hs_err_pid83592.log](https://github.com/async-profiler/async-profiler/files/13652623/hs_err_pid83592.log)

also when I'm using other permutation

if I replace 

````
profiler.execute("start,event=cpu,file=startup-cpu-profile.html,interval=1000000,filter");
````

It works but the flamegraph is empty

<img width="1490" alt="image" src="https://github.com/async-profiler/async-profiler/assets/59146036/8920dc3f-aead-4a2c-8349-320f1b20ba21">

any ideas ?

**Comment by apangin** [comment] 2023-12-12 21:18
According to the crash log, the bug happened with JDK 17.0.8 on macOS/ARM in `StubRoutines::SafeFetch32`.

That's the exact duplicate of #817 and has been already fixed.

**Closed** 2023-12-12 21:19 UTC
Labels: duplicate
