### ISSUE TITLE
Jattach hangs unexpectedly

### ISSUE THREAD

**Issue by JakubStrawa** [async-profiler/async-profiler#762] opened 2023-07-04 13:55 UTC
Hi, 
I’m running async-profiler 2.9 repeatedly within a loop with a '-d 900' parameter to monitor a Tomcat server. After a couple of days, the process randomly freezes and blocks JVM in a way that even the `jcmd` cannot connect to the JVM process. I ran `strace` to debug what’s going on and it looks like this:

<details><summary>Faulty Environment</summary>
<p>

```
[root][faulty-prod][buffer] strace /tmp/async-profiler-2.9-linux-x64/build/jattach 2298855 load /tmp/async-profiler-2.9-linux-x64/build/libasyncProfiler.so true start,file=/tmp/buffer/output.jfr,,event=wall,threads,log=/tmp/async-profiler-log.375982.2298855
execve("/tmp/async-profiler-2.9-linux-x64/build/jattach", ["/tmp/async-profiler-2.9-linux-x6"..., "2298855", "load", "/tmp/async-profiler-2.9-linux-x6"..., "true", "start,file=/tmp/buffer/output"...], 0x7ffe5d3ffa18 /* 21 vars */) = 0
brk(NULL)                               = 0x1370000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffdde682d70) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=47062, ...}) = 0
mmap(NULL, 47062, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f7c40be2000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300A\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0\20\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0", 32, 848) = 32
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\30x\346\264ur\f|Q\226\236i\253-'o"..., 68, 880) = 68
fstat(3, {st_mode=S_IFREG|0755, st_size=2029592, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7c40be0000
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0\20\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0", 32, 848) = 32
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\30x\346\264ur\f|Q\226\236i\253-'o"..., 68, 880) = 68
mmap(NULL, 2037344, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f7c409ee000
mmap(0x7f7c40a10000, 1540096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7f7c40a10000
mmap(0x7f7c40b88000, 319488, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19a000) = 0x7f7c40b88000
mmap(0x7f7c40bd6000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e7000) = 0x7f7c40bd6000
mmap(0x7f7c40bdc000, 13920, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f7c40bdc000
close(3)                                = 0
arch_prctl(ARCH_SET_FS, 0x7f7c40be1540) = 0
mprotect(0x7f7c40bd6000, 16384, PROT_READ) = 0
mprotect(0x7f7c40c1b000, 4096, PROT_READ) = 0
munmap(0x7f7c40be2000, 47062)           = 0
geteuid()                               = 0
getegid()                               = 0
brk(NULL)                               = 0x1370000
brk(0x1391000)                          = 0x1391000
openat(AT_FDCWD, "/proc/2298855/status", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "Name:\tjava\nUmask:\t0022\nState:\tS "..., 1024) = 1024
read(3, "-7\nMems_allowed:\t00000000,000000"..., 1024) = 389
read(3, "", 1024)                       = 0
close(3)                                = 0
stat("/proc/self/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/2298855/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/self/ns/ipc", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/2298855/ns/ipc", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/self/ns/mnt", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/2298855/ns/mnt", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
setresgid(-1, 998, -1)                  = 0
setresuid(-1, 1001, -1)                 = 0
stat("/proc/2298855/root/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f7c40a31090}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
stat("/proc/2298855/root/tmp/.com_ibm_tools_attach/2298855/attachInfo", 0x7ffdde682850) = -1 ENOENT (No such file or directory)
stat("/proc/2298855/root/tmp/.java_pid2298855", {st_mode=S_IFSOCK|0600, st_size=0, ...}) = 0
socket(AF_UNIX, SOCK_STREAM, 0)         = 3
connect(3, {sa_family=AF_UNIX, sun_path="/proc/2298855/root/tmp/.java_pid2298855"}, 110) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0), ...}) = 0
write(1, "Connected to remote JVM\n", 24Connected to remote JVM
) = 24
write(3, "1\0", 2)                      = 2
write(3, "load\0", 5)                   = 5
write(3, "/tmp/async-profiler-2.9-linux-x6"..., 60) = 60
write(3, "true\0", 5)                   = 5
write(3, "start,file=/tmp/buffer/output"..., 145) = 145
read(3,

```
</p>
</details>

On healthy environments this command is able to finish without any issues. 

<details><summary>Healthy Environment</summary>
<p>

```
[root][healthy-prod][buffer] strace /tmp/async-profiler-2.9-linux-x64/build/jattach 816239 load /tmp/async-profiler-2.9-linux-x64/build/libasyncProfiler.so true start,file=/tmp/buffer/output.jfr,,event=wall,threads,log=/tmp/async-profiler-log.123456789
execve("/tmp/async-profiler-2.9-linux-x64/build/jattach", ["/tmp/async-profiler-2.9-linux-x6"..., "816239", "load", "/tmp/async-profiler-2.9-linux-x6"..., "true", "start,file=/tmp/buffer/bigpictur"...], 0x7ffd49c8b848 /* 21 vars */) = 0
brk(NULL)                               = 0x1e45000
arch_prctl(0x3001 /* ARCH_??? */, 0x7fff50eb38b0) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=47062, ...}) = 0
mmap(NULL, 47062, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8d660cd000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300A\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0\20\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0", 32, 848) = 32
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\30x\346\264ur\f|Q\226\236i\253-'o"..., 68, 880) = 68
fstat(3, {st_mode=S_IFREG|0755, st_size=2029592, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8d660cb000
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0\20\0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0", 32, 848) = 32
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0\30x\346\264ur\f|Q\226\236i\253-'o"..., 68, 880) = 68
mmap(NULL, 2037344, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8d65ed9000
mmap(0x7f8d65efb000, 1540096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7f8d65efb000
mmap(0x7f8d66073000, 319488, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19a000) = 0x7f8d66073000
mmap(0x7f8d660c1000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e7000) = 0x7f8d660c1000
mmap(0x7f8d660c7000, 13920, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8d660c7000
close(3)                                = 0
arch_prctl(ARCH_SET_FS, 0x7f8d660cc540) = 0
mprotect(0x7f8d660c1000, 16384, PROT_READ) = 0
mprotect(0x7f8d66106000, 4096, PROT_READ) = 0
munmap(0x7f8d660cd000, 47062)           = 0
geteuid()                               = 0
getegid()                               = 0
brk(NULL)                               = 0x1e45000
brk(0x1e66000)                          = 0x1e66000
openat(AT_FDCWD, "/proc/816239/status", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(3, "Name:\tjava\nUmask:\t0022\nState:\tS "..., 1024) = 1024
read(3, "s_allowed:\t00000000,00000000,000"..., 1024) = 386
read(3, "", 1024)                       = 0
close(3)                                = 0
stat("/proc/self/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/816239/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/self/ns/ipc", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/816239/ns/ipc", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/self/ns/mnt", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/816239/ns/mnt", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
setresgid(-1, 998, -1)                  = 0
setresuid(-1, 1001, -1)                 = 0
stat("/proc/816239/root/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f8d65f1c090}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
stat("/proc/816239/root/tmp/.com_ibm_tools_attach/816239/attachInfo", 0x7fff50eb3390) = -1 ENOENT (No such file or directory)
stat("/proc/816239/root/tmp/.java_pid816239", {st_mode=S_IFSOCK|0600, st_size=0, ...}) = 0
socket(AF_UNIX, SOCK_STREAM, 0)         = 3
connect(3, {sa_family=AF_UNIX, sun_path="/proc/816239/root/tmp/.java_pid816239"}, 110) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0), ...}) = 0
write(1, "Connected to remote JVM\n", 24Connected to remote JVM
) = 24
write(3, "1\0", 2)                      = 2
write(3, "load\0", 5)                   = 5
write(3, "/tmp/async-profiler-2.9-linux-x6"..., 60) = 60
write(3, "true\0", 5)                   = 5
write(3, "start,file=/tmp/buffer/output"..., 145) = 145
read(3, "0\nreturn code: 200\n", 8191)  = 19
read(3, "", 8172)                       = 0
write(1, "JVM response code = 0\nreturn cod"..., 39JVM response code = 0
return code: 200
) = 39
read(3, "", 8192)                       = 0
write(1, "\n", 1
)                       = 1
close(3)                                = 0
exit_group(200)                         = ?
+++ exited with 200 +++

```
</p>
</details> 

Additionally, hanged jattach is creating another tomcat process, which after killing is just restarting and hanging again. 

```
tomcat   2298855  201 59.2 45605416 38504380 ?   Sl   Jun08 55327:08 /usr/lib/jvm/zulu11-ca-amd64/bin/java -Djava.util.logging.config.file=/usr/share/tomcat8/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dcom.sun.management.jmxremote.ssl=false -DdisableLoggerFactoryQueue=true -Dcom.sun.management.jmxremote=true -Dcom.mchange.v2.c3p0.management.ExcludeIdentityToken=true -Dcom.sun.management.jmxremote.access.file=/usr/share/tomcat8/conf/jmxremote.access -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.password.file=/usr/share/tomcat8/conf/jmxremote.password -Djava.rmi.server.hostname=IP -Djava.net.preferIPv4Stack=true -DJDBC_CONNECTION_STRING= -Dperfino.userDirectory=/var/log/perfino -XX:+HeapDumpOnOutOfMemoryError -Xmx31g -Xms31g -XX:-OmitStackTraceInFastThrow -XX:MaxDirectMemorySize=2g -XX:-ReduceInitialCardMarks -XX:NativeMemoryTracking=detail -XX:MaxMetaspaceSize=2g -Xss768k -XX:ConcGCThreads=4 -XX:+UseStringDeduplication -XX:+UseG1GC -XX:HeapDumpPath=/tmp/heapdumps -Xlog:gc*:/usr/share/tomcat8/logs/gc.log:time,uptime,tags:filecount=10,filesize=100M -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0022 -Dignore.endorsed.dirs= -classpath /usr/share/tomcat8/bin/bootstrap.jar:/usr/share/tomcat8/bin/tomcat-juli.jar -Dcatalina.base=/usr/share/tomcat8 -Dcatalina.home=/usr/share/tomcat8 -Djava.io.tmpdir=/usr/share/tomcat8/temp org.apache.catalina.startup.Bootstrap start
tomcat   2451918  0.0  0.0   2496   516 ?        S    Jun08   0:00 /tmp/async-profiler-2.9-linux-x64/build/jattach 2298855 load /tmp/async-profiler-2.9-linux-x64/build/libasyncProfiler.so true stop,file=/tmp/buffer/output-111-prod-2023-06-08-13-31-51.jfr,,log=/tmp/async-profiler-log.2444133.2298855
```
```
ubuntu@faulty-prod:/tmp$ ps aux | grep profiler
ubuntu   1843183  0.0  0.0   9200   724 pts/0    S+   11:56   0:00 grep --color=auto profiler
root     2444133  0.0  0.0   2616  1920 ?        S    Jun08   0:00 /bin/sh /tmp/async-profiler/profiler.sh -e wall -f /tmp/buffer/output-2023-06-08-13-31-51.jfr -t -d 900 2298855
tomcat   2451918  0.0  0.0   2496   516 ?        S    Jun08   0:00 /tmp/async-profiler-2.9-linux-x64/build/jattach 2298855 load /tmp/async-profiler-2.9-linux-x64/build/libasyncProfiler.so true stop,file=/tmp/buffer/output-2023-06-08-13-31-51.jfr,,log=/tmp/async-profiler-log.2444133.2298855
```

Issues started after migrating from async-profiler 1.8, which didn’t cause such issues.
Command I use:
`profiler.sh -e wall -f output-timestamp.jfr -t -d 900 PID`
I access profiler.sh by a symbolic link to entire async-profiler directory if that matters.

JVM flags:
```
-XX:CICompilerCount=4 -XX:ConcGCThreads=4 -XX:G1ConcRefinementThreads=8 -XX:G1HeapRegionSize=8388608 -XX:GCDrainStackTargetSize=64 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdumps -XX:InitialHeapSize=33285996544 -XX:+ManagementServer -XX:MarkStackSize=4194304 -XX:MaxDirectMemorySize=2147483648 -XX:MaxHeapSize=33285996544 -XX:MaxMetaspaceSize=2147483648 -XX:MaxNewSize=19964887040 -XX:MinHeapDeltaBytes=8388608 -XX:NativeMemoryTracking=detail -XX:NonNMethodCodeHeapSize=5836300 -XX:NonProfiledCodeHeapSize=122910970 -XX:-OmitStackTraceInFastThrow -XX:ProfiledCodeHeapSize=122910970 -XX:-ReduceInitialCardMarks -XX:ReservedCodeCacheSize=251658240 -XX:+SegmentedCodeCache -XX:ThreadStackSize=768 -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseFastUnorderedTimeStamps -XX:+UseG1GC -XX:+UseStringDeduplication
```

The only reliable way to fix this I found is to restart the entire JVM (Tomcat) process.
I would be grateful for any help.

**Comment by apangin** [comment] 2023-07-04 14:25
Seems like a duplicate of #708.
The deadlock has been fixed in mainline. You may try [async-profiler 2.10 pre-release](https://github.com/async-profiler/async-profiler/releases/tag/v2.10).

**Closed by apangin** 2023-07-04 14:25 UTC

**Comment by JakubStrawa** [comment] 2023-07-05 07:43
Thank you @apangin, hopefully 2.10 will fix my issue.
